import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from './components/Sidebar'


export const metadata = {
  title: "Gloom Shine Assesment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
